plugins:
  Meniole/command-start-stop@development:
    skipBotEvents: false
  Meniole/command-demo@development:
  Meniole/command-wallet@development:
  Meniole/command-query@development:
  Meniole/text-conversation-rewards@development:
    skipBotEvents: false
    with:
      incentives:
        collaboratorOnlyPaymentInvocation: false
        contentEvaluator:
          openAi:
            endpoint: "https://openrouter.ai/api/v1"
            model: "deepseek/deepseek-chat-v3-0324:free"
        userExtractor: {}
        dataPurge: {}
        formattingEvaluator: {}
        payment: {}
        githubComment: {}
        reviewIncentivizer: {}
        simplificationIncentivizer: {}
        externalContent:
          llmImageModel:
            model: meta-llama/llama-4-maverick:free
          llmWebsiteModel:
            model: deepseek/deepseek-chat-v3-0324:free
  Meniole/daemon-disqualifier@development:
  Meniole/text-vector-embeddings@development:
    with:
      demoFlag: true
